# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_desk', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
