# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desk',
            new_name='task_desc',
        ),
    ]
